# Generated by Django 4.1.6 on 2023-02-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='이름')),
                ('country', models.CharField(max_length=70, verbose_name='나라')),
                ('main', models.CharField(max_length=70, verbose_name='메인분류')),
                ('soup', models.CharField(max_length=70, verbose_name='국물')),
                ('Spicy', models.CharField(max_length=70, verbose_name='맵기')),
                ('temperature', models.CharField(max_length=70, verbose_name='온도')),
                ('weight', models.CharField(max_length=70, verbose_name='무게')),
                ('chocie', models.CharField(max_length=70, verbose_name='선택')),
            ],
        ),
    ]
