# Generated by Django 4.1.6 on 2023-02-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_foodlist_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='language',
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='Spicy',
            field=models.CharField(blank=True, choices=[('매움', '매움'), ('보통', '보통'), ('순함', '순함')], max_length=50, verbose_name='맵기'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='chocie',
            field=models.CharField(blank=True, choices=[('선택사항', '선택사항'), ('선택사항', '선택사항')], max_length=50, verbose_name='선택'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='country',
            field=models.CharField(blank=True, choices=[('한식', '한식'), ('일식', '일식')], max_length=50, verbose_name='나라'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='main',
            field=models.CharField(blank=True, choices=[('면', '면'), ('밥', '밥')], max_length=50, verbose_name='메인분류'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='soup',
            field=models.CharField(blank=True, choices=[('국물 있음', '국물 있음'), ('국물 조금', '국물 조금'), ('국물 없음', '국물 없음')], max_length=50, verbose_name='국물'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='temperature',
            field=models.CharField(blank=True, choices=[('시원한', '시원한'), ('따뜻한', '따뜻한')], max_length=50, verbose_name='온도'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='weight',
            field=models.CharField(blank=True, choices=[('무거운 음식', '무거운 음식'), ('가벼운 음식', '가벼운 음식')], max_length=50, verbose_name='무게'),
        ),
    ]
