# Generated by Django 4.1.6 on 2023-02-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_foodlist_language_alter_foodlist_spicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='Spicy',
            field=models.CharField(blank=True, choices=[('spicy', '매움'), ('normal', '보통'), ('mild', '순함')], max_length=50, verbose_name='맵기'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='chocie',
            field=models.CharField(blank=True, choices=[('vegan', '비건'), ('fastfood', '패스트푸드')], max_length=50, verbose_name='선택'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='country',
            field=models.CharField(blank=True, choices=[('korean', '한식'), ('Japanese', '일식'), ('Chinese', '중식'), ('Western', '양식'), ('Asian', '아시안'), ('Mexican', '맥시칸')], max_length=50, verbose_name='나라'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='main',
            field=models.CharField(blank=True, choices=[('noodle', '면'), ('rice', '밥'), ('bread', '빵')], max_length=50, verbose_name='메인분류'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='soup',
            field=models.CharField(blank=True, choices=[('yes', '국물 있음'), ('little', '국물 쪼금'), ('no', '국물 없음')], max_length=50, verbose_name='국물'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='temperature',
            field=models.CharField(blank=True, choices=[('cool', 'cool'), ('hot', 'hot')], max_length=50, verbose_name='온도'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='weight',
            field=models.CharField(blank=True, choices=[('heavy', 'heavy'), ('light', 'light')], max_length=50, verbose_name='무게'),
        ),
    ]
