# Generated by Django 4.1.6 on 2023-02-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_foodlist_spicy_alter_foodlist_chocie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='chocie',
        ),
    ]
