# Generated by Django 4.1.6 on 2023-02-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_foodlist_country_foodlist_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='Spicy',
            field=models.CharField(choices=[('spicy', '매움'), ('normal', '보통'), ('mild', '순함')], max_length=10, verbose_name='맵기'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='main',
            field=models.CharField(choices=[('noodle', '면'), ('rice', '밥'), ('bread', '빵')], max_length=10, verbose_name='메인분류'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='soup',
            field=models.CharField(choices=[('yes', '국물 있음'), ('little', '국물 쪼금'), ('no', '국물 없음')], max_length=10, verbose_name='국물'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='temperature',
            field=models.CharField(choices=[('cool', '차갑게'), ('warm', '적당히 따뜻하게'), ('hot', '뜨거울 정도로')], max_length=10, verbose_name='온도'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='weight',
            field=models.CharField(choices=[('heavy', '무거움'), ('light', '가벼움')], max_length=10, verbose_name='무게'),
        ),
    ]
