# Generated by Django 4.1.6 on 2023-02-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='NULL'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
