# Generated by Django 4.1.6 on 2023-03-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_foodlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(default='아직 답변이 없습니다. 빠른 시일내에 답변해 드리겠습니다.'),
        ),
    ]
