# Generated by Django 4.1.6 on 2023-03-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('is_save', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='question',
            name='nickname',
            field=models.CharField(default='', max_length=30, verbose_name='nickname'),
        ),
    ]
