# Generated by Django 4.1.6 on 2023-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_save_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='save',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
