# Generated by Django 4.1.6 on 2023-03-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=30, verbose_name='name'), max_length=30, verbose_name='nickname'),
        ),
    ]
